// flow-typed signature: 5ef9b4449e460a3b612ca628bd820b1f
// flow-typed version: <<STUB>>/@fortawesome/fontawesome_v^1.1.4/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/fontawesome/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/fontawesome/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome/index.es'>;
}
declare module '@fortawesome/fontawesome/index' {
  declare module.exports: $Exports<'@fortawesome/fontawesome'>;
}
declare module '@fortawesome/fontawesome/index.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome'>;
}
