// flow-typed signature: 5b8d9f530e32da06b3ab84d4d407108d
// flow-typed version: <<STUB>>/@fortawesome/react-fontawesome_v^0.0.17/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/react-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/react-fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/react-fontawesome/examples/explicit/src/App' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/explicit/src/index' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/explicit/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/external/public/fa-solid' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/external/src/App' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/external/src/index' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/external/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/library/src/App' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/library/src/index' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/examples/library/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/rollup.config' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/src/__mocks__/logger' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/src/components/__tests__/FontAwesomeIcon.test' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/src/components/FontAwesomeIcon' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/src/converter' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/src/index' {
  declare module.exports: any;
}

declare module '@fortawesome/react-fontawesome/src/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/react-fontawesome/examples/explicit/src/App.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/explicit/src/App'>;
}
declare module '@fortawesome/react-fontawesome/examples/explicit/src/index.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/explicit/src/index'>;
}
declare module '@fortawesome/react-fontawesome/examples/explicit/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/explicit/src/registerServiceWorker'>;
}
declare module '@fortawesome/react-fontawesome/examples/external/public/fa-solid.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/external/public/fa-solid'>;
}
declare module '@fortawesome/react-fontawesome/examples/external/src/App.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/external/src/App'>;
}
declare module '@fortawesome/react-fontawesome/examples/external/src/index.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/external/src/index'>;
}
declare module '@fortawesome/react-fontawesome/examples/external/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/external/src/registerServiceWorker'>;
}
declare module '@fortawesome/react-fontawesome/examples/library/src/App.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/library/src/App'>;
}
declare module '@fortawesome/react-fontawesome/examples/library/src/index.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/library/src/index'>;
}
declare module '@fortawesome/react-fontawesome/examples/library/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/examples/library/src/registerServiceWorker'>;
}
declare module '@fortawesome/react-fontawesome/index' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome'>;
}
declare module '@fortawesome/react-fontawesome/index.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome'>;
}
declare module '@fortawesome/react-fontawesome/rollup.config.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/rollup.config'>;
}
declare module '@fortawesome/react-fontawesome/src/__mocks__/logger.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/src/__mocks__/logger'>;
}
declare module '@fortawesome/react-fontawesome/src/components/__tests__/FontAwesomeIcon.test.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/src/components/__tests__/FontAwesomeIcon.test'>;
}
declare module '@fortawesome/react-fontawesome/src/components/FontAwesomeIcon.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/src/components/FontAwesomeIcon'>;
}
declare module '@fortawesome/react-fontawesome/src/converter.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/src/converter'>;
}
declare module '@fortawesome/react-fontawesome/src/index.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/src/index'>;
}
declare module '@fortawesome/react-fontawesome/src/logger.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/src/logger'>;
}
