// flow-typed signature: 7f5797ad112ea4d0afc06f364c459080
// flow-typed version: <<STUB>>/hex-rgba_v1.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hex-rgba'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hex-rgba' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hex-rgba/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hex-rgba/index' {
  declare module.exports: $Exports<'hex-rgba'>;
}
declare module 'hex-rgba/index.js' {
  declare module.exports: $Exports<'hex-rgba'>;
}
declare module 'hex-rgba/test.js' {
  declare module.exports: $Exports<'hex-rgba/test'>;
}
