// flow-typed signature: f377815a353b8619d80972fc7dabcfdd
// flow-typed version: <<STUB>>/istanbul-reports_v^1.3.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'istanbul-reports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'istanbul-reports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'istanbul-reports/lib/clover/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/cobertura/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/html/annotator' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/html/assets/block-navigation' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/html/assets/sorter' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/html/assets/vendor/prettify' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/html/helpers' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/html/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/html/insertion-text' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/json-summary/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/json/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/lcov/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/lcovonly/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/none/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/teamcity/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/text-lcov/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/text-summary/index' {
  declare module.exports: any;
}

declare module 'istanbul-reports/lib/text/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'istanbul-reports/index' {
  declare module.exports: $Exports<'istanbul-reports'>;
}
declare module 'istanbul-reports/index.js' {
  declare module.exports: $Exports<'istanbul-reports'>;
}
declare module 'istanbul-reports/lib/clover/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/clover/index'>;
}
declare module 'istanbul-reports/lib/cobertura/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/cobertura/index'>;
}
declare module 'istanbul-reports/lib/html/annotator.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/html/annotator'>;
}
declare module 'istanbul-reports/lib/html/assets/block-navigation.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/html/assets/block-navigation'>;
}
declare module 'istanbul-reports/lib/html/assets/sorter.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/html/assets/sorter'>;
}
declare module 'istanbul-reports/lib/html/assets/vendor/prettify.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/html/assets/vendor/prettify'>;
}
declare module 'istanbul-reports/lib/html/helpers.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/html/helpers'>;
}
declare module 'istanbul-reports/lib/html/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/html/index'>;
}
declare module 'istanbul-reports/lib/html/insertion-text.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/html/insertion-text'>;
}
declare module 'istanbul-reports/lib/json-summary/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/json-summary/index'>;
}
declare module 'istanbul-reports/lib/json/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/json/index'>;
}
declare module 'istanbul-reports/lib/lcov/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/lcov/index'>;
}
declare module 'istanbul-reports/lib/lcovonly/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/lcovonly/index'>;
}
declare module 'istanbul-reports/lib/none/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/none/index'>;
}
declare module 'istanbul-reports/lib/teamcity/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/teamcity/index'>;
}
declare module 'istanbul-reports/lib/text-lcov/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/text-lcov/index'>;
}
declare module 'istanbul-reports/lib/text-summary/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/text-summary/index'>;
}
declare module 'istanbul-reports/lib/text/index.js' {
  declare module.exports: $Exports<'istanbul-reports/lib/text/index'>;
}
