// flow-typed signature: f1ac9781cedac9c856611702d20df09a
// flow-typed version: <<STUB>>/react-deprecate_v^0.1.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-deprecate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-deprecate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-deprecate/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-deprecate/lib/index.js' {
  declare module.exports: $Exports<'react-deprecate/lib/index'>;
}
