// flow-typed signature: a403f3117216e763fb8a51e955b58b3d
// flow-typed version: <<STUB>>/shevyjs_v1.1.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shevyjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shevyjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shevyjs/dist/constants/index' {
  declare module.exports: any;
}

declare module 'shevyjs/dist/index' {
  declare module.exports: any;
}

declare module 'shevyjs/dist/index.umd' {
  declare module.exports: any;
}

declare module 'shevyjs/dist/index.umd.min' {
  declare module.exports: any;
}

declare module 'shevyjs/dist/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shevyjs/dist/constants/index.js' {
  declare module.exports: $Exports<'shevyjs/dist/constants/index'>;
}
declare module 'shevyjs/dist/index.js' {
  declare module.exports: $Exports<'shevyjs/dist/index'>;
}
declare module 'shevyjs/dist/index.umd.js' {
  declare module.exports: $Exports<'shevyjs/dist/index.umd'>;
}
declare module 'shevyjs/dist/index.umd.min.js' {
  declare module.exports: $Exports<'shevyjs/dist/index.umd.min'>;
}
declare module 'shevyjs/dist/utils/index.js' {
  declare module.exports: $Exports<'shevyjs/dist/utils/index'>;
}
