// flow-typed signature: c09f638d1a17bdf57bda7b9b6c26bf3a
// flow-typed version: <<STUB>>/strip-units_v0.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-units'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-units' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'strip-units/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'strip-units/index' {
  declare module.exports: $Exports<'strip-units'>;
}
declare module 'strip-units/index.js' {
  declare module.exports: $Exports<'strip-units'>;
}
declare module 'strip-units/test.js' {
  declare module.exports: $Exports<'strip-units/test'>;
}
