// flow-typed signature: ab30bfdbb990504250463e4f45002478
// flow-typed version: <<STUB>>/stylelint-config-growcss_v^1.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-growcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-growcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-growcss/index' {
  declare module.exports: $Exports<'stylelint-config-growcss'>;
}
declare module 'stylelint-config-growcss/index.js' {
  declare module.exports: $Exports<'stylelint-config-growcss'>;
}
